version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/set-permissions.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 120
      runas: ec2-user

  # ValidateService 임시 비활성화 (디버깅용)
  # ValidateService:
  #   - location: scripts/health-check.sh
  #     timeout: 180
  #     runas: ec2-user
